apiVersion: v1
data:
  dbconn: bW9uZ29kYjovLyRVU0VSTkFNRTokUEFTU1dPUkRAMDU3ZDIwMzMtYzE3OS00MmY1LTkzM2EtZWEwODdkMTIxOTI1LTAuYmxpanRsZmQwNWpkaW1vb21kaWcuZGF0YWJhc2VzLmFwcGRvbWFpbi5jbG91ZDozMDgwOSwwNTdkMjAzMy1jMTc5LTQyZjUtOTMzYS1lYTA4N2QxMjE5MjUtMS5ibGlqdGxmZDA1amRpbW9vbWRpZy5kYXRhYmFzZXMuYXBwZG9tYWluLmNsb3VkOjMwODA5L2libWNsb3VkZGI/YXV0aFNvdXJjZT1hZG1pbiZyZXBsaWNhU2V0PXJlcGxzZXQ=
  password: c2t5bGVydGVzdGluZw==
  username: YWRtaW4=
  db_name: aWJtY2xvdWRkYg==
  bff_url: aHR0cHM6Ly9jbG91ZC1mdW5kLm15Y2x1c3Rlci0xMzg0MjktZTdiOWYwZDE0NzAwZDU0NzhjNTQyNTYyNDlmZjVlODUtMDAwMC51cy1zb3V0aC5jb250YWluZXJzLmFwcGRvbWFpbi5jbG91ZA==
  backend_url: aHR0cDovL2Nsb3VkLWZ1bmQtYmFja2VuZC1zZXJ2aWNlOjg1MDA=
  frontend_url: aHR0cHM6Ly9jbG91ZC1mdW5kLm15Y2x1c3Rlci0xMzg0MjktZTdiOWYwZDE0NzAwZDU0NzhjNTQyNTYyNDlmZjVlODUtMDAwMC51cy1zb3V0aC5jb250YWluZXJzLmFwcGRvbWFpbi5jbG91ZA==
  app_id_credentials: eyJjbGllbnRJZCI6ICI5MmM2YjJmOC04Yzc2LTQ2OTQtOTgxOC1lYzI2ZjM4MzMzNDciLCAib2F1dGhTZXJ2ZXJVcmwiOiAiaHR0cHM6Ly91cy1zb3V0aC5hcHBpZC5jbG91ZC5pYm0uY29tL29hdXRoL3Y0Lzg3MzE2NDNjLWM5YTgtNDU2MC1iYWRjLWIwMzkxMGQ5YWEwOCIsICJwcm9maWxlc1VybCI6ICJodHRwczovL3VzLXNvdXRoLmFwcGlkLmNsb3VkLmlibS5jb20iLCAic2VjcmV0IjogIk5qRTJPVFZpT1RZdE9UazVZUzAwT0RNd0xXSmtOR1V0TmpBMU9ESTBNVGt6TVdFMSIsICJ0ZW5hbnRJZCI6ICI4NzMxNjQzYy1jOWE4LTQ1NjAtYmFkYy1iMDM5MTBkOWFhMDgifQ==
  app_id_sign_in: aHR0cHM6Ly91cy1zb3V0aC5hcHBpZC5jbG91ZC5pYm0uY29tL29hdXRoL3Y0Lzg3MzE2NDNjLWM5YTgtNDU2MC1iYWRjLWIwMzkxMGQ5YWEwOC9hdXRob3JpemF0aW9uP2NsaWVudF9pZD05MmM2YjJmOC04Yzc2LTQ2OTQtOTgxOC1lYzI2ZjM4MzMzNDcmcmVzcG9uc2VfdHlwZT1zaWduX3VwJnJlZGlyZWN0X3VyaT1odHRwczovL2Nsb3VkLWZ1bmQubXljbHVzdGVyLTEzODQyOS1lN2I5ZjBkMTQ3MDBkNTQ3OGM1NDI1NjI0OWZmNWU4NS0wMDAwLnVzLXNvdXRoLmNvbnRhaW5lcnMuYXBwZG9tYWluLmNsb3VkL2libS9ibHVlbWl4L2FwcGlkL2NhbGxiYWNrJnNjb3BlPWFwcGlkX2RlZmF1bHQ=
  crk_id: ''
  kp_instance_id: MGE2NzRlMWYtZDY1YS00OTNmLWFmNjUtMDU0YjBhMzA0ZGQ5
  kms_url_secret: Y3JuOnYxOmJsdWVtaXg6cHVibGljOmttczp1cy1zb3V0aDphLzEwZDU5NTNhNGFlM2JjYjU4OGU2MmI3MjRhYTQzZDcwOjBhNjc0ZTFmLWQ2NWEtNDkzZi1hZjY1LTA1NGIwYTMwNGRkOTprZXk6YTQ2ZGFlNjktMmJmYy00NDBhLTk4NjQtZThhOGYxODNlODI3
  API_KEY: dUU3dnYyNmY2Wm5kV0Q4QzdKQTdtOHBQQkh4MVd0RXY0aTg1M3hiRzNDSGQ=
  cert_pem: MIIDDzCCAfegAwIBAgIJANEH58y2/kzHMA0GCSqGSIb3DQEBCwUAMB4xHDAaBgNV BAMME0lCTSBDbG91ZCBEYXRhYmFzZXMwHhcNMTgwNjI1MTQyOTAwWhcNMjgwNjIy
    MTQyOTAwWjAeMRwwGgYDVQQDDBNJQk0gQ2xvdWQgRGF0YWJhc2VzMIIBIjANBgkq hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA8lpaQGzcFdGqeMlmqjffMPpIQhqpd8qJ
    Pr3bIkrXJbTcJJ9uIckSUcCjw4Z/rSg8nnT13SCcOl+1to+7kdMiU8qOWKiceYZ5 y+yZYfCkGaiZVfazQBm45zBtFWv+AB/8hfCTdNF7VY4spaA3oBE2aS7OANNSRZSK
    pwy24IUgUcILJW+mcvW80Vx+GXRfD9Ytt6PRJgBhYuUBpgzvngmCMGBn+l2KNiSf weovYDCD6Vngl2+6W9QFAFtWXWgF3iDQD5nl/n4mripMSX6UG/n6657u7TDdgkvA
    1eKI2FLzYKpoKBe5rcnrM7nHgNc/nCdEs5JecHb1dHv1QfPm6pzIxwIDAQABo1Aw TjAdBgNVHQ4EFgQUK3+XZo1wyKs+DEoYXbHruwSpXjgwHwYDVR0jBBgwFoAUK3+X
    Zo1wyKs+DEoYXbHruwSpXjgwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOC AQEAJf5dvlzUpqaix26qJEuqFG0IP57QQI5TCRJ6Xt/supRHo63eDvKw8zR7tlWQ
    lV5P0N2xwuSl9ZqAJt7/k/3ZeB+nYwPoyO3KvKvATunRvlPBn4FWVXeaPsG+7fhS qsejmkyonYw77HRzGOzJH4Zg8UN6mfpbaWSsyaExvqknCp9SoTQP3D67AzWqb1zY
    doqqgGIZ2nxCkp5/FXxF/TMb55vteTQwfgBy60jVVkbF7eVOWCv0KaNHPF5hrqbN i+3XjJ7/peF3xMvTMoy35DcT3E2ZeSVjouZs15O90kI3k2daS2OHJABW0vSj4nLz
    +PQzp/B9cQmOO8dCe049Q3oaUA==
kind: Secret
metadata:
  name: cloud-fund-environment-secrets
type: Opaque
